src/Entity/Compte.php
<?php

namespace App\Entity;

use App\Repository\CompteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CompteRepository::class)]
class Compte
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $id_utilisateur = null;

    #[ORM\Column(length: 35)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::DATE_MUTABLE )]
    private ?\DateTimeInterface $date_de_creation = null;

    #[ORM\Column]
    private ?int $nbr_followers = null;

    #[ORM\Column]
    private ?int $nbr_followings = null;

    #[ORM\Column]
    private ?int $nbr_produits_publies = null;

    #[ORM\Column]
    private ?int $banned = null;

    #[ORM\Column(length: 255)]
    private ?string $profile_image = null;
     
    #[ORM\OneToMany(mappedBy: "followed", targetEntity: RelationFollow::class)]
    private Collection $followers;
 
    #[ORM\OneToMany(mappedBy: "follower", targetEntity: RelationFollow::class)]
    private Collection $followings;

    #[ORM\Column(length: 255 , nullable:true)]
    private ?string $bio = null;

    public function getFollowers(): Collection
    {
        return $this->followers;
    }

    public function setFollowers(Collection $followers): self
    {
        $this->followers = $followers;
        return $this;
    }

    public function getFollowings(): Collection
    {
        return $this->followings;
    }

    public function setFollowings(Collection $followings): self
    {
        $this->followings = $followings;
        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $Id): self
    {
        $this->Id = $Id;

        return $this;
    }

    public function getIdUtilisateur(): ?int
    {
        return $this->id_utilisateur;
    }

    public function setIdUtilisateur(int $id_utilisateur): self
    {
        $this->id_utilisateur = $id_utilisateur;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateDeCreation(): ?\DateTimeInterface
    {
        return $this->date_de_creation;
    }

    public function setDateDeCreation(\DateTimeInterface $date_de_creation): self
    {
        $this->date_de_creation = $date_de_creation;

        return $this;
    }

    public function getNbrFollowers(): ?int
    {
        return $this->nbr_followers;
    }

    public function setNbrFollowers(int $nbr_followers): self
    {
        $this->nbr_followers = $nbr_followers;

        return $this;
    }

    public function getNbrFollowings(): ?int
    {
        return $this->nbr_followings;
    }

    public function setNbrFollowings(int $nbr_followings): self
    {
        $this->nbr_followings = $nbr_followings;

        return $this;
    }

    public function getNbrProduitsPublies(): ?int
    {
        return $this->nbr_produits_publies;
    }

    public function setNbrProduitsPublies(int $nbr_produits_publies): self
    {
        $this->nbr_produits_publies = $nbr_produits_publies;

        return $this;
    }

    public function getBanned(): ?int
    {
        return $this->banned;
    }

    public function setBanned(int $banned): self
    {
        $this->banned = $banned;

        return $this;
    }

    public function getProfileImage(): ?string
    {
        return $this->profile_image;
    }

    public function setProfileImage(string $profile_image): self
    {
        $this->profile_image = $profile_image;

        return $this;
    }

    public function getBio(): ?string
    {
        return $this->bio;
    }

    public function setBio(string $bio): self
    {
        $this->bio = $bio;

        return $this;
    }

   

}

src/Form/CompteType.php
<?php

namespace App\Form;

use App\Entity\Compte;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;
use Eckinox\TinymceBundle\Form\Type\TinymceType ; 


class CompteType extends AbstractType
{

    // test
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
           // ->add('id_utilisateur') 
            ->add('nom')
         /*   ->add('date_de_creation')
            ->add('nbr_followers')
            ->add('nbr_followings')
            ->add('nbr_produits_publies')
            ->add('banned') */
            ->add('profile_image', FileType::class, [
                'label' => 'Image de profile',
                'mapped' => false,
                'required' => false,
                'attr' => [
                    'accept' => '.jpg, .jpeg, .png',
                ],    'constraints' => [
                    new File([
                        'maxSize' => '2M',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid JPG, JPEG or PNG image',
                    ])
                ],
            
            ])
            ->add('bio', TinymceType::class, [
                'attr' => [
                    'toolbar' => 'bold italic underline | bullist numlist emoticons', // Ajouter le plugin 'emoticons' à la barre d'outils
                    'plugins' => 'emoticons', // Activer le plugin 'emoticons'
                    'emoticons_data' => '[{"shortcut": "🙂", "url": "https://example.com/emoji/smile.png"}, {"shortcut": "🙁", "url": "https://example.com/emoji/sad.png"}]' ,// Définir la liste des emojis disponibles
                    'label' => 'bio'
                ],
            ])
            


        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Compte::class,
        ]);
    }
}

src/Controller/CompteController.php
<?php

namespace App\Controller;

use App\Entity\Compte;
use App\Entity\RelationFollow;
use App\Form\CompteType;
use App\Repository\CompteRepository;
use App\Repository\RelationFollowRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface ;
use Symfony\Component\HttpFoundation\Request as HttpFoundationRequest;
use GuzzleHttp\Client;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\DomCrawler\Crawler;

#[Route('/compte')]
class CompteController extends AbstractController
{
    #[Route('/comptes', name: 'app_compte_index', methods: ['GET'])]
    public function index(CompteRepository $compteRepository , PaginatorInterface $paginator, Request $request
    ): Response
    {     $comptes = $paginator->paginate($compteRepository->findAll(),
        $request->query->getInt('page',1),
        4) ;
        $pageCount = $comptes->getPageCount();
        return $this->render('compte/index.html.twig', [
            'comptes' => $comptes,
            'pageCount' => $pageCount,

        ]);
    }
    #[Route('/search-comptes', name: 'search_comptes')]
    public function searchComptes(Request $request, CompteRepository $compteRepository, SerializerInterface $serializer,PaginatorInterface $paginator)
    {

        if ($request->isXmlHttpRequest()) {
    
            $searchTerm = $request->request->get('search_field');
    
            // Vérifier si le champ de recherche est vide
            if (empty($searchTerm)) {
                 
        $comptes = $compteRepository->findAll();
        // Utilisez la méthode paginate pour paginer les résultats
        $comptes = $paginator->paginate(
           $comptes,
            $request->query->getInt('page', 1), // Numéro de page
            4 // Nombre de résultats par page
        );
        $pageCount = $comptes->getPageCount();
    
     
                $html = $this->renderView('compte/index.html.twig', [
                    'comptes' => $comptes,
            'pageCount' => $pageCount,
                     
                ]);
    
                $crawler = new Crawler($html);
                $compteList = $crawler->filter('#comptes-list')->html();
                        // retourner les résultats au format JSON
                        return new JsonResponse($compteList);
            }
            $comptes = $paginator->paginate(
                $compteRepository->findbyname($searchTerm),$request->query->getInt('page', 1), // Numéro de page
                4 // Nombre de résultats par page
            );
            
            // transformer les résultats en HTML
            $pageCount = $comptes->getPageCount();
    
     
                $html = $this->renderView('compte/index.html.twig', [
                    'comptes' => $comptes,
                    'pageCount' => $pageCount,
                             
                ]);
    
            $crawler = new Crawler($html);
    $compteList = $crawler->filter('#comptes-list')->html();
            // retourner les résultats au format JSON
            return new JsonResponse($compteList);
        } else {
            // si la requête n'est pas une requête AJAX, afficher la page des discussions
            $comptes = $paginator->paginate(
                $compteRepository->findAll(),
                $request->query->getInt('page', 1), // Numéro de page
                4 // Nombre de résultats par page
            );
            $pageCount = $comptes->getPageCount();
    
     
                $html = $this->renderView('compte/index.html.twig', [
                    'comptes' => $comptes,
                    'pageCount' => $pageCount,
                             
                ]);
        }
    }
    #[Route('/admin', name: 'app_compte_index_admin', methods: ['GET'])]
    public function indexadmin(CompteRepository $compteRepository): Response
    {
        return $this->render('compte/index_admin.html.twig', [
            'comptes' => $compteRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_compte_new', methods: ['GET', 'POST'])]
    public function new(Request $request, CompteRepository $compteRepository): Response
    {
        $compte = new Compte();
        $form = $this->createForm(CompteType::class, $compte);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $compte->setDateDeCreation(new \DateTime('now'));
            $compte->setNbrFollowers(0);
            $compte->setNbrFollowings(0);
            $compte->setNbrProduitsPublies(0);
            $compte->setBanned(0);
            $imageFile = $form->get('profile_image')->getData();

            if ($imageFile) {
                $imagesDirectory = 'C:/xampp/htdocs/img';
                $originalFilename = $imageFile->getClientOriginalName();
                $filenameWithoutSpaces = str_replace(' ', '_', $originalFilename);

                try {
                   
                   $imageFile->move($imagesDirectory, $filenameWithoutSpaces);
                } catch (FileException $e) {
                    // Handle exception
                }
                
                $compte->setProfileImage($filenameWithoutSpaces);
               }

            $compteRepository->save($compte, true);

            return $this->redirectToRoute('app_compte_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('compte/new.html.twig', [
            'compte' => $compte,
            'form' => $form,
        ]);
    }
    #[Route('/admin/{id}', name: 'app_compte_show_admin', methods: ['GET'])]
    public function shows(Compte $compte ,CompteRepository $rep1 , RelationFollowRepository $rep2 ): Response
    {   
        $comptelogin = $rep1->find(1);
        $tablerelation = $rep2->checkFollow($comptelogin,$compte);
        $followings = $compte->getFollowings(); 
        $followerss = [];
        $followingss = [];
        $followers = $compte->getFollowers(); 
        foreach ($followers as $f) {
           
            $followerss[] = $f->getFollower() ;
        }
        foreach ($followings as $f) {
           
            $followingss[] = $f->getFollowed() ;
        }
        return $this->render('compte/show_admin.html.twig', [
            'compte' => $compte, 
            'tablerelation' => $tablerelation,
            'followings' => $followingss ,
            'followers' => $followerss ,
         
        ]);
    }
    #[Route('/{id}', name: 'app_compte_show', methods: ['GET'])]
    public function show(Compte $compte ,CompteRepository $rep1 , RelationFollowRepository $rep2 ): Response
    {   
        $comptelogin = $rep1->find(1);
        $tablerelation = $rep2->checkFollow($comptelogin,$compte);
        $followings = $compte->getFollowings(); 
        $followerss = [];
        $followingss = [];
        $followers = $compte->getFollowers(); 
        foreach ($followers as $f) {
           
            $followerss[] = $f->getFollower() ;
        }
        foreach ($followings as $f) {
           
            $followingss[] = $f->getFollowed() ;
        }
        return $this->render('compte/show.html.twig', [
            'compte' => $compte, 
            'tablerelation' => $tablerelation,
            'followings' => $followingss ,
            'followers' => $followerss ,
         
        ]);
    }

    
   
    #[Route('/{id}/edit', name: 'app_compte_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Compte $compte, CompteRepository $compteRepository): Response
    {
        $form = $this->createForm(CompteType::class, $compte);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $imageFile = $form->get('profile_image')->getData();
        
                    if ($imageFile) {
                        
                        $imagesDirectory = 'C:/xampp/htdocs/img';
                        $originalFilename = $imageFile->getClientOriginalName();
                        $filenameWithoutSpaces = str_replace(' ', '_', $originalFilename);
        
                        
                           
                           $imageFile->move($imagesDirectory, $filenameWithoutSpaces);
                      
                        
                        $compte->setProfileImage($filenameWithoutSpaces);
                        }

            $compteRepository->save($compte, true);


            return $this->redirectToRoute('app_compte_show', ['id' => $compte->getId()], Response::HTTP_SEE_OTHER);

        }

        return $this->renderForm('compte/edit.html.twig', [
            'compte' => $compte,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_compte_delete', methods: ['POST'])]
    public function delete(Request $request, Compte $compte, CompteRepository $compteRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$compte->getId(), $request->request->get('_token'))) {
            $compteRepository->remove($compte, true);
        }

        return $this->redirectToRoute('app_compte_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/', name: 'app_compte_home', methods: ['GET'])]
    public function Home(CompteRepository $compteRepository): Response
    {
        return $this->render('compte/home.html.twig', [
            'comptes' => $compteRepository->findAll(),
        ]);
    }

    public function unfollow(Request $request, Compte $compte , CompteRepository $rep1 , RelationFollowRepository $rep2): Response
    {
        
        
        // Find the logged-in user's compte.
        //$user = $this->getUser()->getCompte();
        $comptelogin = $rep1->find(1);
        

templates/compte/_delete_form.html.twig
<form method="post" action="{{ path('app_compte_delete', {'id': compte.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ compte.id) }}">
    <button class="btn_3">Delete</button>
</form>

templates/compte/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<!-- breadcrumb start-->
    <section class="breadcrumb breadcrumb_bg">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="breadcrumb_iner">
                        <div class="breadcrumb_iner_item">
                            <h2>Mon Compte</h2>
                            <p>welcome <span>-</span>back</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb end -->
     <!-- feature_part start-->
    <section class="feature_part padding_top">
        <div class="container">

    <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="section_tittle text-center">
                        <h2>Mon compte</h2>
                    </div>
                </div>
    </div>
   <!-- 
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Id_utilisateur</th>
                <th>Nom</th>
                <th>Date_de_creation</th>
                <th>Nbr_followers</th>
                <th>Nbr_followings</th>
                <th>Nbr_produits_publies</th>
                <th>Banned</th>
                <th>Profile_image</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for compte in comptes %}
            <tr>
                <td>{{ compte.id }}</td>
                <td>{{ compte.idUtilisateur }}</td>
                <td>{{ compte.nom }}</td>
                <td>{{ compte.dateDeCreation ? compte.dateDeCreation|date('Y-m-d') : '' }}</td>
                <td>{{ compte.nbrFollowers }}</td>
                <td>{{ compte.nbrFollowings }}</td>
                <td>{{ compte.nbrProduitsPublies }}</td>
                <td>{{ compte.banned }}</td>
                <td>{{ compte.profileImage }}</td>
                <td>
                    <a href="{{ path('app_compte_show', {'id': compte.id}) }}">show</a>
                    <a href="{{ path('app_compte_edit', {'id': compte.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table> 
    -->
<div class="row align-items-center justify-content-between">
    <div class="col-lg-4 col-md-4 col-sm-6">
        <a href="{{ path('app_compte_show', {'id': 1}) }}" style="text-decoration: none;">
            <div class="single_feature_post_text">
                <h3>Mon Profile</h3>
                <a href="{{ path('app_compte_show', {'id': 1}) }}" class="feature_btn">EXPLORE NOW <i class="fas fa-play"></i></a>
            </div>
        </a>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-6">
        <a href="" style="text-decoration: none;">
            <div class="single_feature_post_text">
                <h3>Mes Information Personnels</h3>
                <a href="" class="feature_btn">EXPLORE NOW <i class="fas fa-play"></i></a>
            </div>
        </a>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-6">
        <a href="{{ path('app_compte_index') }}" style="text-decoration: none;">
            <div class="single_feature_post_text">
                <h3>comptes</h3>
                <a href="{{ path('app_compte_index') }}" class="feature_btn">EXPLORE NOW <i class="fas fa-play"></i></a>
            </div>
        </a>
    </div>
</div>





    <a href="{{ path('app_compte_new') }}">Create new</a>
    </div>
    </section>

{% endblock %}

templates/compte/index_admin.html.twig
{% extends 'baseadmin.html.twig' %}
{% block body %}
<div class="card">
                                            <div class="card-header">
                                                <h5>Comptes</h5>
                                                <span>affichage des Comptes</span>
                                                <div class="card-header-right">
                                                    <ul class="list-unstyled card-option" style="width: 30px;">
                                                        <li><i class="fa fa open-card-option fa-wrench"></i></li>
                                                        <li><i class="fa fa-window-maximize full-card"></i></li>
                                                        <li><i class="fa fa-minus minimize-card"></i></li>
                                                        <li><i class="fa fa-refresh reload-card"></i></li>
                                                        <li><i class="fa fa-trash close-card"></i></li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="card-block table-border-style">
                                                <div class="table-responsive">
                                                    <table class="table">
                                                        <thead>
                                                            <tr class="bg-danger">
                                                                <th>id</th>
                                                                <th>id utilisateur</th>
                                                                <th>Nom</th>
                                                                <th>Nbr Produits</th>
                                                                <th>Nbr Followers</th>
                                                                <th>Nbr Followings</th>
                                                                <th>Date de creation </th>
                                                                <th>Banned</th>
                                                                <th>Actions</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                         {% for c in comptes %}
            <tr>
                <td class="table-active">{{ c.id }}</td>
                <td>{{ c.idutilisateur }}</td>
                <td>{{ c.nom }}</td>
                <td>{{ c.nbrProduitsPublies }}</td>
                <td>{{ c.nbrFollowers }}</td>
                <td>{{ c.nbrFollowings }}</td>
                <td>{{ c.dateDeCreation    ? c.dateDeCreation|date('Y-m-d') : '' }}</td>
                <td>{{c.banned}} </td>
                <td>
                    
                    <button class="btn waves-effect waves-light btn-inverse btn-outline-inverse" onclick="location.href='{{ path('app_compte_show_admin', {'id': c.id}) }}'">Afficher</button>
                    <br>
                    <br>
                    {% if c.banned == 0 %}
                
                    <button class="btn waves-effect waves-light btn-success btn-outline-success" onclick="location.href='{{ path('app_banned', {'id': c.id}) }}'">Banner</button>
                    {% else %}
                                        <button class="btn waves-effect waves-light btn-success btn-outline-success" onclick="location.href='{{ path('app_unbanned', {'id': c.id}) }}'">unbanner</button>
                    {% endif %}

                    
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
                                                    </table>

                                                </div>

                                            </div>
                                            
                                        </div>

    {% endblock %}

templates/compte/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Swappy {{compte.nom}} {% endblock %}

{% block body %}
  <!-- breadcrumb start-->
    <section class="breadcrumb breadcrumb_bg">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="breadcrumb_iner">
                        <div class="breadcrumb_iner_item">
                            <h2>Mon Compte</h2>
                            <p>welcome <span>-</span>back</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb end -->
     <!-- feature_part start-->
    <section class="feature_part padding_top">
        <div class="container">

   <!--

    {{ include('compte/_delete_form.html.twig') }}
    -->
  <div class="row py-5 px-4">
   <div class="col-md-5 mx-auto">
    <!-- Profile widget -->
     <div class="bg-white shadow rounded overflow-hidden">
      <div class="px-4 pt-0 pb-4 cover">
       <div class="media align-items-end profile-head"> 
       <div class="profile mr-3">
       <img src="http://localhost/img/{{compte.profileImage}}" alt="..." width="130" class="rounded mb-2 img-thumbnail">
      {% if compte.id == 1 %}
    <a href="{{ path('app_compte_edit', {'id': compte.id}) }}" class="btn btn-outline-dark btn-sm btn-block">Edit profile</a>
{% else %}
  {% if tablerelation|length > 0 %}
    <a href="{{ path('app_unfollow', {'id': compte.id}) }}" class="btn btn-outline-dark btn-sm btn-block">Unfollow</a>

  {% else %}
  <a href="{{ path('app_follow', {'id': compte.id}) }}" class="btn btn-outline-dark btn-sm btn-block">Follow</a>
  {% endif %}
{% endif %}
       </div> 
       <div class="media-body mb-5 text-white"> 
       <h4 class="mt-0 mb-0">{{compte.nom}}</h4>
        <p class="small mb-4"> <i class="fas fa-map-marker-alt mr-2"></i>tunis</p> 
        </div>
         </div> 
         </div>
          <div class="bg-light p-4 d-flex justify-content-end text-center"> 
          <ul class="list-inline mb-0"> 
          <li class="list-inline-item"> 
          <h5 class="font-weight-bold mb-0 d-block">{{compte.nbrProduitsPublies}}</h5>
          <small class="text-muted"> 
          <i class="fas fa-image mr-1"></i>
          Articles</small> </li>
           <li class="list-inline-item"> 
           <h5 class="font-weight-bold mb-0 d-block">{{compte.nbrFollowers}}</h5><small class="text-muted" id="Followers"> <i class="fas fa-user mr-1"></i>Followers</small> </li>
            <li class="list-inline-item"> <h5 class="font-weight-bold mb-0 d-block">{{compte.nbrFollowings}}</h5><small class="text-muted" id="Followings"> <i class="fas fa-user mr-1"></i>Followings</small> </li>
             </ul> 
             </div>
              <div class="px-4 py-3"> 
              <h5 class="mb-0">About</h5> 
              <div class="p-4 rounded shadow-sm bg-light">
               <p class="font-italic mb-0">{{compte.bio|raw}}</p>
                
                  </div> 
                  </div> 
                  <div class="py-4 px-4">
                   <div class="d-flex align-items-center justify-content-between mb-3">
                    <h5 class="mb-0" id="recent-photos">Recent photos</h5>
                    <a href="#" class="btn btn-link text-muted">Show all</a> </div>
                   <!--                    Followers row             -->
                   <div class="blog-author" id="followers-row"  style="display:none;">
                    {% for f in followers %}
                    {% if f.banned == 0%}
                     <div class="media align-items-center">
                     <img src="http://localhost/img/{{f.profileImage}}" alt="photo" width="60px" height="60px">
                     <div class="media-body" style="padding: 25px;">
                        <a href="{{ path('app_compte_show', {'id': f.id}) }}">
                           <h5>{{f.nom}}</h5>
                        </a>
                     </div>
                  </div>
                  {% endif %}
                  {% endfor %}
                  </div>
                  <!--                    Followings row             -->
                   <div class="blog-author" id="followings-row"  style="display:none;">
                    {% for f in followings %}
                    {% if f.banned == 0%}
                     <div class="media align-items-center">
                     <img src="http://localhost/img/{{f.profileImage}}" alt="photo" width="60px" height="60px">
                     <div class="media-body" style="padding: 25px;">
                        <a href="{{ path('app_compte_show', {'id': f.id}) }}">
                           <h5>{{f.nom}}</h5>
                        </a>
                     </div>
                  </div>
                  {% endif %}
                  {% endfor %}
                  </div>
                  <!--               Main Row              -->
                     <div class="row" id="row"> 
                     <div class="col-lg-6 mb-2 pr-lg-1">
                     <img src="https://images.unsplash.com/photo-1469594292607-7bd90f8d3ba4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" alt="" class="img-fluid rounded shadow-sm"></div> 
                     <div class="col-lg-6 mb-2 pl-lg-1">
                     <img src="https://images.unsplash.com/photo-1493571716545-b559a19edd14?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" alt="" class="img-fluid rounded shadow-sm"></div> <div class="col-lg-6 pr-lg-1 mb-2"><img src="https://images.unsplash.com/photo-1453791052107-5c843da62d97?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="" class="img-fluid rounded shadow-sm"></div> 
                     <div class="col-lg-6 pl-lg-1">
                     <img src="https://images.unsplash.com/photo-1475724017904-b712052c192a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" alt="" class="img-fluid rounded shadow-sm"></div>
                      </div> 
                      </div>
                       </div>
                        </div>
                        
</div>
</div>
    </section>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function() {
    // Hide the row when Followers is clicked
    $("#Followers").click(function() {
      $("#row").hide();
      $('#followers-row').show();
      $('#followings-row').hide();
      // Change the text of Recent Photos to Followers
      $("#recent-photos").text("Followers");
      
    });
  });
</script>
<script>
  $(document).ready(function() {
    // Hide the row when Followings is clicked 
    $("#Followings").click(function() {
      $("#row").hide();
      $('#followers-row').hide();
      $('#followings-row').show();
      // Change the text of Recent Photos to Followers
      $("#recent-photos").text("Followings");
      
    });
  });
</script>


{% endblock %}