src/Entity/RelationFollow.php
<?php

namespace App\Entity;

use App\Repository\RelationFollowRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RelationFollowRepository::class)]
class RelationFollow
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $id_follower = null;

    #[ORM\Column]
    private ?int $id_followed = null;

    #[ORM\ManyToOne(targetEntity: Compte::class)]
    #[ORM\JoinColumn(name: "id_follower", referencedColumnName: "id")]
    private ?Compte $follower = null;

    #[ORM\ManyToOne(targetEntity: Compte::class)]
    #[ORM\JoinColumn(name: "id_followed", referencedColumnName: "id")]
    private ?Compte $followed = null;

    
    public function getFollower(): ?Compte
    {
        return $this->follower;
    }

    public function setFollower(?Compte $follower): self
    {
        $this->follower = $follower;

        return $this;
    }

    public function getFollowed(): ?Compte
    {
        return $this->followed;
    }

    public function setFollowed(?Compte $followed): self
    {
        $this->followed = $followed;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdFollower(): ?int
    {
        return $this->id_follower;
    }

    public function setIdFollower(int $id_follower): self
    {
        $this->id_follower = $id_follower;

        return $this;
    }

    public function getIdFollowed(): ?int
    {
        return $this->id_followed;
    }

    public function setIdFollowed(int $id_followed): self
    {
        $this->id_followed = $id_followed;

        return $this;
    }
}

src/Form/RelationFollowType.php
<?php

namespace App\Form;

use App\Entity\RelationFollow;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RelationFollowType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('id_follower')
            ->add('id_followed')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => RelationFollow::class,
        ]);
    }
}

src/Controller/RelationFollowController.php
<?php

namespace App\Controller;

use App\Entity\RelationFollow;
use App\Form\RelationFollowType;
use App\Repository\RelationFollowRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/relation/follow')]
class RelationFollowController extends AbstractController
{
    #[Route('/', name: 'app_relation_follow_index', methods: ['GET'])]
    public function index(RelationFollowRepository $relationFollowRepository): Response
    {
        return $this->render('relation_follow/index.html.twig', [
            'relation_follows' => $relationFollowRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_relation_follow_new', methods: ['GET', 'POST'])]
    public function new(Request $request, RelationFollowRepository $relationFollowRepository): Response
    {
        $relationFollow = new RelationFollow();
        $form = $this->createForm(RelationFollowType::class, $relationFollow);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $relationFollowRepository->save($relationFollow, true);

            return $this->redirectToRoute('app_relation_follow_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('relation_follow/new.html.twig', [
            'relation_follow' => $relationFollow,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_relation_follow_show', methods: ['GET'])]
    public function show(RelationFollow $relationFollow): Response
    {
        return $this->render('relation_follow/show.html.twig', [
            'relation_follow' => $relationFollow,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_relation_follow_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, RelationFollow $relationFollow, RelationFollowRepository $relationFollowRepository): Response
    {
        $form = $this->createForm(RelationFollowType::class, $relationFollow);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $relationFollowRepository->save($relationFollow, true);

            return $this->redirectToRoute('app_relation_follow_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('relation_follow/edit.html.twig', [
            'relation_follow' => $relationFollow,
            'form' => $form,
        ]);
    }

   #[Route('/{id}', name: 'app_relation_follow_delete', methods: ['POST'])]
    public function delete(Request $request, RelationFollow $relationFollow, RelationFollowRepository $relationFollowRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$relationFollow->getId(), $request->request->get('_token'))) {
            $relationFollowRepository->remove($relationFollow, true);
        }

        return $this->redirectToRoute('app_relation_follow_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/relation_follow/_delete_form.html.twig
<form method="post" action="{{ path('app_relation_follow_delete', {'id': relation_follow.id}) }}" onsubmit="return confirm('Are you sure you want to unfollow?');">

    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ relation_follow.id) }}">
    <button class="btn">Delete</button>

</form>

templates/relation_follow/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/relation_follow/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit RelationFollow{% endblock %}

{% block body %}
    <h1>Edit RelationFollow</h1>

    {{ include('relation_follow/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_relation_follow_index') }}">back to list</a>

    {{ include('relation_follow/_delete_form.html.twig') }}
{% endblock %}

templates/relation_follow/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}RelationFollow index{% endblock %}

{% block body %}
    <h1>RelationFollow index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Id_follower</th>
                <th>Id_followed</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for relation_follow in relation_follows %}
            <tr>
                <td>{{ relation_follow.id }}</td>
                <td>{{ relation_follow.idFollower }}</td>
                <td>{{ relation_follow.idFollowed }}</td>
                <td>
                    <a href="{{ path('app_relation_follow_show', {'id': relation_follow.id}) }}">show</a>
                    <a href="{{ path('app_relation_follow_edit', {'id': relation_follow.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_relation_follow_new') }}">Create new</a>
{% endblock %}

templates/relation_follow/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New RelationFollow{% endblock %}

{% block body %}
    <h1>Create new RelationFollow</h1>

    {{ include('relation_follow/_form.html.twig') }}

    <a href="{{ path('app_relation_follow_index') }}">back to list</a>
{% endblock %}

templates/relation_follow/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}RelationFollow{% endblock %}

{% block body %}
    <h1>RelationFollow</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ relation_follow.id }}</td>
            </tr>
            <tr>
                <th>Id_follower</th>
                <td>{{ relation_follow.idFollower }}</td>
            </tr>
            <tr>
                <th>Id_followed</th>
                <td>{{ relation_follow.idFollowed }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_relation_follow_index') }}">back to list</a>

    <a href="{{ path('app_relation_follow_edit', {'id': relation_follow.id}) }}">edit</a>

    {{ include('relation_follow/_delete_form.html.twig') }}
{% endblock %}