src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentaireRepository::class)]
class Commentaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $id_user = null;

    #[ORM\Column(length: 255)]
    private ?string $username = null;

    #[ORM\Column(length: 255)]
    private ?string $sujet_com = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_com = null;

    #[ORM\ManyToOne(inversedBy: 'commentaires')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Publication $id_pub = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdUser(): ?int
    {
        return $this->id_user;
    }

    public function setIdUser(int $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getSujetCom(): ?string
    {
        return $this->sujet_com;
    }

    public function setSujetCom(string $sujet_com): self
    {
        $this->sujet_com = $sujet_com;

        return $this;
    }

    public function getDateCom(): ?\DateTimeInterface
    {
        return $this->date_com;
    }

    public function setDateCom(\DateTimeInterface $date_com): self
    {
        $this->date_com = $date_com;

        return $this;
    }

    public function getIdPub(): ?Publication
    {
        return $this->id_pub;
    }

    public function setIdPub(?Publication $id_pub): self
    {
        $this->id_pub = $id_pub;

        return $this;
    }
}

src/Entity/Publication.php
<?php

namespace App\Entity;

use App\Repository\PublicationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PublicationRepository::class)]
class Publication
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $id_user = null;

    #[ORM\Column(length: 255)]
    #[Assert\Regex(
        pattern: '/^[A-Za-z]+$/',
        message: 'The title must contain only letters.',
    )]
    private ?string $titre_pub = null;

    #[ORM\Column(length: 255)]
    private ?string $contenu_pub = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_pub = null;

    #[ORM\Column]
    private ?int $nb_signals = null;

    #[ORM\OneToMany(mappedBy: 'id_pub', targetEntity: Commentaire::class)]
    private Collection $commentaires;

    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdUser(): ?int
    {
        return $this->id_user;
    }

    public function setIdUser(int $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getTitrePub(): ?string
    {
        return $this->titre_pub;
    }

    public function setTitrePub(string $titre_pub): self
    {
        $this->titre_pub = $titre_pub;

        return $this;
    }

    public function getContenuPub(): ?string
    {
        return $this->contenu_pub;
    }

    public function setContenuPub(string $contenu_pub): self
    {
        $this->contenu_pub = $contenu_pub;

        return $this;
    }

    public function getDatePub(): ?\DateTimeInterface
    {
        return $this->date_pub;
    }

    public function setDatePub(\DateTimeInterface $date_pub): self
    {
        $this->date_pub = $date_pub;

        return $this;
    }

    public function getNbSignals(): ?int
    {
        return $this->nb_signals;
    }

    public function setNbSignals(int $nb_signals): self
    {
        $this->nb_signals = $nb_signals;

        return $this;
    }
    public function getNbSignalsCount(): int
    {
        return $this->getNbSignals()->count();
    }
    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaires(): Collection
    {
        
        return $this->commentaires;
    }
    public function getCommentairesCount(): int
    {
        return $this->getCommentaires()->count();
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires->add($commentaire);
            $commentaire->setIdPub($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getIdPub() === $this) {
                $commentaire->setIdPub(null);
            }
        }

        return $this;
    }
    public function __toString()
    {

        return $this->titre_pub;
    }
}

src/Form/Publication1Type.php
<?php

namespace App\Form;

use App\Entity\Publication;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class Publication1Type extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('id_user')
            ->add('titre_pub')
            ->add('contenu_pub')
            ->add('date_pub')
            ->add('nb_signals')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Publication::class,
        ]);
    }
}

src/Controller/Publication1Controller.php
<?php

namespace App\Controller;

use App\Entity\Publication;
use App\Form\Publication1Type;
use App\Repository\PublicationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/publication1')]
class Publication1Controller extends AbstractController
{
    #[Route('/', name: 'app_publication1_index', methods: ['GET'])]
    public function index(PublicationRepository $publicationRepository): Response
    {
        return $this->render('publication1/index.html.twig', [
            'publications' => $publicationRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_publication1_new', methods: ['GET', 'POST'])]
    public function new(Request $request, PublicationRepository $publicationRepository): Response
    {
        $publication = new Publication();
        $form = $this->createForm(Publication1Type::class, $publication);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $publicationRepository->save($publication, true);

            return $this->redirectToRoute('app_publication1_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('publication1/new.html.twig', [
            'publication' => $publication,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_publication1_show', methods: ['GET'])]
    public function show(Publication $publication): Response
    {$comment=$publication->getCommentaires();
        return $this->render('publication1/show.html.twig', [
            'publication' => $publication,
            'comment'=> $comment,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_publication1_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Publication $publication, PublicationRepository $publicationRepository): Response
    {
        $form = $this->createForm(Publication1Type::class, $publication);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $publicationRepository->save($publication, true);

            return $this->redirectToRoute('app_publication1_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('publication1/edit.html.twig', [
            'publication' => $publication,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_publication1_delete', methods: ['POST'])]
    public function delete(Request $request, Publication $publication, PublicationRepository $publicationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$publication->getId(), $request->request->get('_token'))) {
            $publicationRepository->remove($publication, true);
        }

        return $this->redirectToRoute('app_publication1_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/publication1/_delete_form.html.twig
<form method="post" action="{{ path('app_publication1_delete', {'id': publication.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ publication.id) }}">
        <button class="btn waves-effect waves-light btn-danger btn-outline-danger">Delete</button>

</form>

templates/publication1/edit.html.twig
{% extends 'back.html.twig' %}

{% block title %}Edit Publication{% endblock %}
{% block body %}
    <h1>Edit Publication</h1>

    <div class="form-container">
        {{ include('publication1/_form.html.twig', {'button_label': 'Update'}) }}

        <div class="button-container">
            <a href="{{ path('app_publication1_index') }}" class="btn-3">Back to List</a>
            {{ include('publication1/_delete_form.html.twig', {'button_label': 'Delete', 'button_class': 'btn-3'}) }}
        </div>
    </div>

    <style>
        .form-container {
            border: 2px solid #ccc;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 2px 2px 5px #ccc;
        }
        
        .button-container {
            display: flex;
            justify-content: space-between;
            margin-top: 20px;
        }
        
        .btn-3 {
            background-color: #4CAF50;
            color: white;
            border: none;
            border-radius: 5px;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
            transition-duration: 0.4s;
        }
        
        .btn-3:hover {
            background-color: white;
            color: #4CAF50;
            border: 2px solid #4CAF50;
        }
    </style>
{% endblock %}

templates/publication1/index.html.twig
{% extends 'back.html.twig' %}

{% block title %}Publication index{% endblock %}

{% block body %}
   <div class="page-wrapper">
                                    <!-- Page-body start -->
                                    <div class="page-body">
                                      <div class="card">
                                            <div class="card-header">
                                                <h5>Publication</h5>
                                                <span>affichage des publications</span>
                                                <div class="card-header-right">
                                                    <ul class="list-unstyled card-option" style="width: 30px;">
                                                        <li><i class="fa fa open-card-option fa-wrench"></i></li>
                                                        <li><i class="fa fa-window-maximize full-card"></i></li>
                                                        <li><i class="fa fa-minus minimize-card"></i></li>
                                                        <li><i class="fa fa-refresh reload-card"></i></li>
                                                        <li><i class="fa fa-trash close-card"></i></li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="card-block table-border-style">
                                                <div class="table-responsive">
                                                    <table class="table">
                                                        <thead>
                                                            <tr class="bg-danger">
                                                                 <th>Id</th>
                <th>Id_user</th>
                <th>Titre_pub</th>
                <th>Contenu_pub</th>
                <th>Date_pub</th>
                <th>Nb_signals</th>
                <th>actions</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                        {% for publication in publications %}
              <tr>
                <td>{{ publication.id }}</td>
                <td>{{ publication.idUser }}</td>
                <td>{{ publication.titrePub }}</td>
                <td>{{ publication.contenuPub }}</td>
                <td>{{ publication.datePub ? publication.datePub|date('Y-m-d') : '' }}</td>
                <td>{{ publication.nbSignals }}</td>
                <td>
                    
                    <button class="btn waves-effect waves-light btn-inverse btn-outline-inverse" onclick="location.href='{{path('app_publication1_show', {'id': publication.id}) }}'">Afficher</button>
                    <br>
                    <br>
                    <button class="btn waves-effect waves-light btn-success btn-outline-success" onclick="location.href='{{  path('app_publication1_edit', {'id': publication.id})  }}'">Modifier</button>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
                                                    </table>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>


<canvas id="myChart" style="width: 1000px; height: 600px"></canvas>

<script>
var xValues = [];
var yValues = [];

{% for publication in publications %}
    xValues.push("{{ publication.titrepub }}");
    yValues.push({{ publication.getCommentairesCount() }});
{% endfor %}

var barColors = [];
for (var i = 0; i < xValues.length; i++) {
    // Génère une couleur aléatoire pour chaque barre
    barColors.push(rgba(${Math.floor(Math.random() * 256)}, ${Math.floor(Math.random() * 256)}, ${Math.floor(Math.random() * 256)}, 0.7));
}

new Chart("myChart", {
  type: "bar",
  data: {
    labels: xValues,
    datasets: [{
      backgroundColor: barColors,
      data: yValues
    }]
  },
  options: {
    legend: {display: false},
    title: {
      display: true,
      text: "Nombre de commentaires par publication"
    },
    scales: {
      yAxes: [{
        ticks: {
          beginAtZero: true
        }
      }]
    }
  }
});
</script>
        

                                                </div>
                         <button class="btn waves-effect waves-light btn-success btn-outline-success" onclick="location.href='{{ path('app_publication1_new') }}'"  > Créer publication </button>


                                            </div>
                                            
                                        </div>
                                        
{% endblock %}

templates/publication1/new.html.twig
{% extends 'back.html.twig' %}

{% block title %}New Publication{% endblock %}

{% block body %}
    <h1>Create new Publication</h1>

    {{ include('publication1/_form.html.twig') }}

    <a href="{{ path('app_publication1_index') }}">back to list</a>
{% endblock %}

templates/publication1/show.html.twig
{% extends 'back.html.twig' %}

{% block title %}Publication{% endblock %}

{% block body %}
   <div class="page-wrapper">
                                    <div class="page-body">
                                        <div class="row">
                                            <div class="col-sm-12">
                                                <div class="card">
                                                    <div class="card-header">
                                                        <h5> publication avec id :{{publication.id}}</h5>
                                                        <span>{{publication.titrePub}}</span>
                                                        <div class="card-header-right">
                                                            <ul class="list-unstyled card-option">
                                                                <li>
                                                                    <i class="fa fa fa-wrench open-card-option"></i>
                                                                </li>
                                                                <li>
                                                                    <i class="fa fa-window-maximize full-card"></i>
                                                                </li>
                                                                <li>
                                                                    <i class="fa fa-minus minimize-card"></i>
                                                                </li>
                                                                <li>
                                                                    <i class="fa fa-refresh reload-card"></i>
                                                                </li>
                                                                <li>
                                                                    <i class="fa fa-trash close-card"></i>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                    <div class="card-block">


                                                        <h5>Contenu de la pub</h5>{{publication.contenuPub}} 
                                                        <br> 
                                                        <h5>Date de publication</h5>{{ publication.datePub ? publication.datePub|date('Y-m-d') : '' }}
                                                        <br> 
                                                        <h5>Nombre de signals</h5>{{publication.nbSignals}}
                                                        <br> 
                                                    
                                                            <button class="btn waves-effect waves-light btn-success btn-outline-success" onclick="location.href='{{ path ('app_publication1_edit', {'id': publication.id})}}'"> Edit </button>
                                                            <button class="btn waves-effect waves-light btn-success btn-outline-success" id="comment" > Commentaires </button>
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                </div>
   

    <button class="btn waves-effect waves-light btn-success btn-outline-success" onclick="location.href='{{path ('app_publication1_index')}}'"> Back to list </button>
 


    {{ include('publication1/_delete_form.html.twig') }}

     <div class="page-wrapper" id="commentaire" style="display:none;"
>
             {% for c in comment %}
                                    <div class="page-body">
                                        <div class="row">
                                            <div class="col-sm-12">
                                                <div class="card">
                                                    <div class="card-header">
                                                        <h5> commentaire avec id :{{c.getId()}}</h5>
                                                        <span>{{c.getUsername()}}</span>
                                                        <div class="card-header-right">
                                                            <ul class="list-unstyled card-option">
                                                                <li>
                                                                    <i class="fa fa fa-wrench open-card-option"></i>
                                                                </li>
                                                                <li>
                                                                    <i class="fa fa-window-maximize full-card"></i>
                                                                </li>
                                                                <li>
                                                                    <i class="fa fa-minus minimize-card"></i>
                                                                </li>
                                                                <li>
                                                                    <i class="fa fa-refresh reload-card"></i>
                                                                </li>
                                                                <li>
                                                                    <i class="fa fa-trash close-card"></i>
                                                                </li>
                                                            </ul>
                                                        </div>
                                                    </div>
                                                    <div class="card-block">


                                                        <h5>Contenu du commenatire </h5>{{c.getSujetCom()}} 
                                                        <br> 
                                                        <h5>Date du comentaire</h5>{{ c.getDateCom() ? c.getDateCom()|date('Y-m-d') : '' }}
                                                        <br> 
                                                        <h5>Nombre de signals</h5>{{publication.nbSignals}}
                                                        <br> 
                                                    
                                                            <button class="btn waves-effect waves-light btn-danger btn-outline-danger" onclick="location.href='{{ path ('app_supprimer', {'id': c.getId()})}}'"> delete </button>
                                                            
                                                    </div>
                                                </div>
                                            </div>

                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                                <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function() {
    // Hide the row when Followers is clicked
    $("#comment").click(function() {
      
      $('#commentaire').show();
     // $('#followings-row').hide();
      // Change the text of Recent Photos to Followers
      //$("#recent-photos").text("Followers");
      
    });
  });
</script>
<script>
{% endblock %}